name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 3 AM UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: cicirello/user-statistician@v1
        with:
          image-file: profile/summary.svg
          category-order: repositories, contributions, languages
          languages-limit: 8
          languages-threshold-stats: 1%
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
